###############################################################################################
#########                           --Database Settings--                             #########
###############################################################################################
dbhost: 127.0.0.1:3306
dbname: emi
dbuser: emi
dbpass: "secret"

###############################################################################################
#########                      --EverMap General Marker Settings--                    #########
###############################################################################################
label_max_length: 20 #Max 50
label_min_length: 2
dynmap_url: localhost:8123

###############################################################################################
#########                              --EverMap Base Marker Settings--               #########
###############################################################################################
base_set_label: "Player bases" # Label for markerset, if you want to update edit dynmap marker.yml
base_limit: 1
base_icon: tower

###############################################################################################
#########                              --EverMap Messages            --               #########
###############################################################################################

# General messages
marker_added_text: "§1Marker got added §aSuccessfully "
marker_added_text_component: "§3[§4Marker§3]"
marker_added_text_component_desc: "§7Marker location"

marker_not_found: "&4Marker could not be found!"
marker_deleted: "&6Marker got deleted!"

# Base messages
base_limit_reach: "&4 Base limit is reached fuck off &8<3"
