###############################################################################################
#########                           --Database Settings--                             #########
###############################################################################################
dbhost: 127.0.0.1:3306
dbname: emi
dbuser: emi
dbpass: "secret"

###############################################################################################
#########                              --EverMap Base Marker Settings--               #########
###############################################################################################
base_set_label: "Player bases" # Label for markerset
base_limit: 1
base_icon: tower
